downloads:
  - data: labels
    manifest: input/manifest/manifest_labels.txt
    mapping: input/mapping/mapping_labels.json
    filename_ending: .xml

  - data: genexpr
    manifest: input/manifest/manifest_genexpr.txt
    mapping: input/mapping/mapping_genexpr.json
    filename_ending: .rna_seq.augmented_star_gene_counts.tsv

  - data: wsi
    manifest: input/manifest/manifest_wsi.txt
    mapping: input/mapping/mapping_wsi.json
    filename_ending: .svs

max_downloads: 2
manifest_dir: input/manifest
raw_data_dir: input/raw
output: input/processed/input.csv